## Homework **Week 5**

1. What does **Pandas** stand for?

    * Stands for either:
        * Panel Data
        * Python Data Analysis

1. What are the **2 collections** used in Pandas?

    The two primary data structures of pandas, *Series and DataFrame*

1. Name **4 things** Pandas can do for us.

    * load
    * manipulate
    * prepare
    * model
    * _here's an extra one: analyze_

1. To permanently sort a DataFrame, **which keyword** should one use with the df.sort() method?

    *inplace=True*

1. What is a **CSV**?

    CSV is stands for *Comma Separated Values* and is a text file used in spreadsheets and databases.

1. When cleaning data what values do we **not like** in our data?

    We don't want *NaNs* or no values.


In [1]:
# mport NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). 

import numpy as np

array0 = np.random.randint(24, 78, size=(2, 3, 2))
print(array0)

[[[72 72]
  [33 59]
  [61 73]]

 [[50 52]
  [42 66]
  [56 42]]]


In [2]:
# Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20
array1 = np.linspace(0,20, num=6)
array1


array([ 0.,  4.,  8., 12., 16., 20.])

In [3]:
#Make a Deep Copy of the above array

import copy
array2 = copy.deepcopy(array1)
array2


array([ 0.,  4.,  8., 12., 16., 20.])

In [4]:
#Concatenate these 3 arrays into a new array named 'newArray'...
array3 = ([[25, 16]])
array4 = ([[11, 2], [13, 4]])
array5 = ([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((array3, array4, array5), axis=0)
print(newArray)

[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [5]:
# Sort 'newArray' in order into 'sortedArray'

sortedArray = np.sort(newArray)
print(sortedArray)

[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [6]:
# Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.

### there is no array named "reshapedArray" and none of my arrays have 4 (or n*4) touples ###


a,b,c,d,e,f = sortedArray
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)


[16 25]
[ 2 11]
[ 4 13]
[ 7 81]
[5 6]
[11 12]


In [27]:
# Combine and sort the following arrays into one called 'comboArray' ...

one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.concatenate((one, two, three))
print(comboArray)

comboArraysort = np.sort(comboArray)
print(comboArraysort)



[10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6  7]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [33]:
# Take 'comboArray' and perform the following slicing activities:
# print sec1 - the 2nd element
sec1 = comboArraysort[1]
print(sec1)

# print sec2 - all elements from the 3rd element to the last
sec2 = comboArraysort[2:]
print(sec2)

# print sec3 - all elements from the 4th to the 14th elements 
### - including the 14th or not?
print(comboArraysort[3:14])

# print sec4 - the last 6 elements
print(comboArraysort[-6:])

# print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end. 
print(comboArraysort[:-9])

# print sec6 - from #20 every even element to the end 
### - is "20" the element number or the number 20?
print(comboArraysort[20::2])

# print sec7 - from the last element moving forward, every 5th element. 
### - how can one move from the last element forward?
print(comboArraysort[::-5])


1
[ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 3  4  5  6  7 10 11 12 13 14 15]
[22 23 24 25 26 27]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16]
[24 26]
[27 22 15 10  3]


In [39]:
import numpy as np 
import pandas as pd

In [50]:
# Using Series, create a DataFrame that looks like this:
Ingredients	= pd.Series(['Flour', 'Milk', 'Eggs', 'Spam'], name='Ingredients')
Quantity = pd.Series([4,1,2,1], name='Quantity')
Unit = pd.Series(['cups', 'cup', 'large', 'can'], name='Unit')

dinner = pd.concat([Ingredients, Quantity, Unit], axis=1)

dinner

# Name: Dinner, dtype: object





Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can

In [63]:
# Take this data and create a DataFrame named studentData

studentData = pd.DataFrame({'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
    })
studentData

Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket

In [66]:
# Add a new column to the DataFrame with the following deserts: 

studentData["Dessert"] = ["Ice Cream", "Cashew Fudge", "Waffels", "Carrot Halwa"]
studentData



Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

        Dessert  
0     Ice Cream  
1  Cashew Fudge  
2       Waffels  
3  Carrot Halwa

In [72]:
# Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

studentData.sort_values(by= ['Name', 'address'], inplace=True)
studentData


Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

        Dessert  
3  Carrot Halwa  
2       Waffels  
0     Ice Cream  
1  Cashew Fudge

In [74]:
#Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:


animals = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
animals.to_csv('cows_and_goats.csv')

df = pd.read_csv('cows_and_goats.csv')
print(df)



  Unnamed: 0  Cows  Goats
0     Year 1    12     22
1     Year 2    20     19


In [79]:
# (A) Using Pandas, make your own .CSV file with data on vegetables and save it. 

veggies = pd.DataFrame({'Green': ['spinach','kale', 'bok choi', 'brussels sprouts'], 'Red': ['radishes', 'beets', 'red carrots', 'tomatos']})

veggies.to_csv('veggies.csv')
veggies

Green          Red
0           spinach     radishes
1              kale        beets
2          bok choi  red carrots
3  brussels sprouts      tomatos

In [85]:
# (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

df1 = pd.read_csv('veggies.csv')
df1 = veggies.replace(to_replace=['tomatos'], value=['cayenne peppers'])
df1

df1.to_csv('veggies_V2.csv')
